### PR TITLE
Map in Transfer could break HTML rendering #61

### LINKED ISSUE #61: [R66] Listing pages are broken in the admin interface
FollowId addition breaks the json included in the html source:

2020-07-31-114046_487x74_scrot

I can only guess it comes from [DbTaskRunner.getJson()](https://github.com/waarp/Waarp-All/blob/v3.4/WaarpR66/src/main/java/org/waarp/openr66/database/data/DbTaskRunner.java#L3791) which uses arrayNode.toString() to generate JSON.

but according to [jackson doc](http://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/node/ArrayNode.html#toString()):

> Method that will produce developer-readable representation of the node; which
> may or may not be as valid JSON. If you want valid JSON output (or output
> formatted using one of other Jackson supported data formats) make sure to use
> ObjectMapper or ObjectWriter to serialize an instance, for example:
> 
>    String json = objectMapper.writeValueAsString(rootNode);

I imagine it also would remove the need to do "manual" cleaning of the json generated.

### PR DESCRIPTION
**Pull request by fredericBregier**
Fix Issue #61 by escaping the Map in TransferInfo and unescaping it while using the map

### CODE REVIEW

**Review by bcarlin — CHANGES_REQUESTED** [review]
These changes indeed fixes the admin transfer listing.

They have, however, an unintended side effect: The json output of the commands have too much excaping:

With the patch applied, I have the following output:
```
➜ ./bin/waarp-r66client.sh server2 send -file foo.txt -to server1 -rule push
[DirectTransfer] Transfer in status:       SUCCESS 
{"command":"DirectTransfer","args":"etc/conf.d/server2/client.xml -file foo.txt -to server1 -rule push ","status":0,"statusTxt":"Transfer in status:       SUCCESS ","remote":"server1","ruleid":"push","statusCode":"O","specialid":-9223372036854775806,"finalPath":"/out/foo.txt","requested":"server1","requester":"server2","fileInformation":"noinfo {\\\"follow\\\":-7298291395239706531}","originalSize":12,"originalPath":"/out/foo.txt","filefinal":"File: /out/foo.txt Ready true isExternal false 0","delay":10399}
```
If I want to get the follow id, i will:
1. parse the main json,
2. get the value of fileInformation
3. get rid of "noinfo "
4. parse the remaining json.

This remaining json is `{\"follow\":-7298291395239706531}`, taking into account the un-escaping done by the parser of the main document.
This is not valid json, and parsing that fails (ex: https://play.golang.org/p/oeW_sZPI3US)

**Comment by fredericBregier** [comment]
FileTransfer is not a JSON but a String, containing a JSON, therefore escaped (since `"` is not valid in a String).
The procedure is that the JSON is the last part (fusion of possible multiple Json) of the final String, and is escaped.
Then it is parsed internally using regex `\{[^\}]*\} to match.

So this is a correct Json in escaped mode.
WDYT?

**Comment by bcarlin** [comment]
Wether I extract the Json part of the string with string manipulation or a regex, this has the same result.

The thing is that what is printed on stdout, `{\\\"follow\\\":-7298291395239706531}` corresponds to the raw string (the underlying value of the String object) `{\"follow\":-7298291395239706531}`, which cannot be parsed.

The valid JSON would be `{"follow":-7298291395239706531}`, so its String representation is just `{\"follow\":-7298291395239706531}`, which explains my "too much escaping comment".

**Comment by fredericBregier** [comment]
I update this MR. I obtain something like:
`{\"follow\":-7298291395239706531}` (both on HTML and output)
So single `\`.
For the correction of FileInfo andTransferInfo, it will be in the last MR since it needs some deep correction (hopefully not too much).
Are you OK with this ?

**Review by bcarlin — APPROVED** [review]

**Pull request merged**
