### PR TITLE
Various small improvements

### PR DESCRIPTION
**Pull request by amottier**
This PR try to fix various minor issues:
- Use HTTPS for third party Maven repositories URL to avoid the need of specific configuration with recent Maven versions.
- Follow recommendation from [https://maven.apache.org/maven-ci-friendly.html](https://maven.apache.org/maven-ci-friendly.html#dependencies) to allow individual module build.
- Update extra-enforcer-rules Maven plugin to benefit from bug fix.
- Remove usage of PhantomJS as Selenium drop support of PhantomJS in version 3.8.0.

Each commit have comments with more details about what have been done.

This PR also include a commit (775b995faec7faa8bd5eb411c6e82e1db73037b3) that is part of #112.

### CODE REVIEW

**Comment by fredericBregier** [comment]
Great ! Thank you !

**Comment by amottier** [comment]
@fredericBregier do you think you will be able to merge this pull request? Please let me know if I can do anything to help. Thanks.

**Comment by fredericBregier** [comment]
@amottier Sorry, I was busy.
I've tested and it seems ok.
It takes some time since I had discovered that my new PC has Firefox as snap and not native, making the tests on HTTP incorrect (issue while having a snap instead of direct package). I've fixed it and it works.

Thank you !

**Comment by amottier** [comment]
Thanks a lot for the merge @fredericBregier :+1: 

I actually so that geckodriver as some know issue related to SNAP packaging in the latest version (https://github.com/mozilla/geckodriver/releases/tag/v0.33.0) and they suggest workarounds (https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html#Running-Firefox-in-an-container-based-package).

**Pull request merged**
